apiVersion: v1
kind: Service
metadata:
  name: fiap-pedidos
  labels:
    app: fiap-pedidos
spec:
  selector:
    app: fiap-pedidos
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer