apiVersion: v1
kind: Service
metadata:
  name: fiap-pedidos
spec:
  selector:
    app.kubernetes.io/name: fiap-pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127