apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pedidos
  labels:
    app: db-pedidos
spec:
  selector:
    matchLabels:
      app: db-pedidos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-pedidos
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-fiap-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-pedidos-pv-claim